### ISSUE TITLE
Error: Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)

### ISSUE THREAD

**Issue by tprafull** [monax/legacy-contracts.js#69]
I want to upload a file to IPFS and generate unique ID by passing IPFS hash.I am passing IPFS hash to solidity program to generate unique ID. When I executed my node program, I got below error.
I am using eris 0.12 , node v6.9.4 

```
{ Error: Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)
    at values.next.then (/home/demoadmin/node_modules/eris-contracts/node_modules/eris-db/node_modules/@nodeguy/json-rpc/lib/index.js:12:38)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.module.exports.loopWhile (/home/demoadmin/node_modules/deasync/index.js:71:11)
    at Function.sleep (/home/demoadmin/node_modules/deasync/index.js:44:19)
    at hexifyAuditdata (/home/demoadmin/Prafull/auditpoc/nodeserver.js:158:32)
    at /home/demoadmin/Prafull/auditpoc/nodeserver.js:669:25
    at Layer.handle [as handle_request] (/home/demoadmin/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/demoadmin/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/demoadmin/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/demoadmin/node_modules/express/lib/router/layer.js:95:5)
    at /home/demoadmin/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/demoadmin/node_modules/express/lib/router/index.js:330:12)
    at next (/home/demoadmin/node_modules/express/lib/router/index.js:271:10)
    at /home/demoadmin/Prafull/auditpoc/nodeserver.js:39:5
    at Layer.handle [as handle_request] (/home/demoadmin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/demoadmin/node_modules/express/lib/router/index.js:312:13)
    at /home/demoadmin/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/demoadmin/node_modules/express/lib/router/index.js:330:12)
    at next (/home/demoadmin/node_modules/express/lib/router/index.js:271:10)
    at Immediate.<anonymous> (/usr/lib/node_modules/multer/lib/make-middleware.js:52:37)
    at runCallback (timers.js:653:20)
    at tryOnImmediate (timers.js:622:5)
  method: 'transactAndHold',
  params:
   [ { priv_key: '811D3FA47CA5767821E15A58B072717D43974474E25E9765D20968D1B6C41066C78D187712835A5034D5A216EA8686601218E88DF6FF15E81AA08AB79AB7CC04',
       address: '7EE9EB8B85FAD66EC31D1FFA74EB994D44C2ABEA',
       data: 'f39b2368000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000002e516d56555451677053787072354c68766b48386b5448473948355745344671437a44576264535a706734534c5a69000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003d42616c616e6365205368656574092232372046656272756172792032303136efbfbd6d22092232382046656272756172792032303135efbfbd6d220909000000',
       gas_limit: 1000000,
       fee: 0 } ],
  code: -32603,
  message: 'Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)' }
Error in converting records Error: Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)
```

**Comment by NodeGuy** [comment]
@benjaminbollen Why would Eris DB complain about a duplicate transaction?

**Comment by DvdChavarri** [comment]
+1 Same Issue. What could be the issue? 
@NodeGuy Good question 

Environment Windows 7: 
 * Eris v0.12
 * Node v7.3.0
 * eris-contracts v0.15.6
 * eris-db v0.15.6
 * solc v0.3.6

Track-trace:

{ Error: Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)
    at values.next.then (C:\Users\dchavarri\.eris\apps\chaintonic\node_modules\eris-db\node_modules\@nodeguy\json-rpc\lib\index.js:12:38)
  method: 'transactAndHold',
  params:
   [ { priv_key: '9A01A1E2E3AEE57213D8DA96E2D2B9399FA9AA4C9B01F4527537F1F5D929D3BD27194EBD487BFEC2ECDE270CCAEA7ECBD0C849400B127CF843933E607D0D5434',
       address: '',
       data: '60606040525b33600060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055505b6... ',
       gas_limit: 1000000,
       fee: 0 } ],
  code: -32603,
  message: 'Error broadcasting transaction: Unknown error returned: Duplicate transaction (ignored)' }

**Comment by benjaminbollen** [comment]
This error indicates that a transaction is received that is identical to a transaction that is still waiting to be committed into a block;  this can either mean that the chain is not further processing blocks and including new transactions; or that identical transactions are being submitted very shortly after one-another before the chain has had a chance to absorb them - note that a transaction should never be identical; the sequence number monotonically increases -

**Comment by NodeGuy** [comment]
Please try running your code again with the environment variable `NODE_DEBUG` set to `eris` and submit the results here.  E.g.,

```
NODE_DEBUG=eris node index.js
```
