### ISSUE TITLE
Error: Account data is not on the proper format:

### ISSUE THREAD

**Issue by test2015deve** [monax/legacy-contracts.js#91]
hi,

after ı created app.js and node it. I got the error below. Do you have any idea why i face with it? 

_**/root/.monax/apps/idi/node_modules/eris-contracts/lib/pipes/dev_pipe.js:58
     throw new Error('Account data is not on the proper format: ' + JSON.stringify(accounts))
     ^

Error: Account data is not on the proper format: {"address":"7661B4349A925EFD98C6830A12A8912C5A2CBD16","pubKey":"5DEF888EEA05A903DBE08AE4E08C3B762FF92132272CBD7E3AEF9CA9F109BAE1","privKey":""}
    at new DevPipe (/root/.monax/apps/idi/node_modules/eris-contracts/lib/pipes/dev_pipe.js:58:12)
    at Object.exports.newContractManagerDev (/root/.monax/apps/idi/node_modules/eris-contracts/index.js:26:14)
    at Object.<anonymous> (/root/.monax/apps/idi/app.js:22:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3**_

**Comment by NodeGuy** [comment]
Please fill out all parts of the issue template.
